### PR TITLE
Highlights download stats

### LINKED ISSUE #285: Highlights of Download stats on main page.
It would be great if we had a script that determines the recently most downloaded zenodo records, similar to [this notebook](https://github.com/NFDI4BIOIMAGE/training/blob/main/notebooks/download_stats.ipynb): and then updates the website [main page](https://github.com/NFDI4BIOIMAGE/training/blob/main/docs/readme.md). For example, it could replace a placeholder such as `{most_downloaded}` with some actual content.

Optional: It could download the most downloaded thing, turn it into a PNG and show it on the main page. This will not work with all contents obviously, but with PPTx or PDFs.

git-bob comment: Given a zenodo record url, how would you automatically download the first file from this zenodo record using the zenodo API and if its a PPT or PDF turn the first slide or page into a PNG?

### PR DESCRIPTION
**Pull request by marabuuu**
Hi @haesleinhuepf, 

This PR closes #285.

Hereby:
- The script reads two recent download statistics files, compares download counts and identifies the record with the highest increase in downloads.
- It extracts the Zenodo record ID from the URL of the most downloaded resource and downloads the associated file from Zenodo

> Note: I hope by downloading the most downloaded resource, we are not biasing the download statistics. We can have a look at it, I hope that much more people are downloading stuff such that it doesn't influence it too much.

- For PDF or PPTX files, the script converts the first page or slide to a PNG image and saves it in a designated folder.
- It updates the README file with a link to the most downloaded resource and embeds the newly created PNG under a specific subheading.
- it is executed every time the book is built.

I am happy to make further adjustments if you want something changed 🌻 

Best,
Mara

### CODE REVIEW

**Review by haesleinhuepf — CHANGES_REQUESTED** [review]
Fantastic @marabuuu, that's super cool!

May I ask for one modification: It would be great if the script respects copyright. For example, we could only copy images from slides if those are licensed CC-BY 4.0  (zenodo has that in the meta-data). And in that case we should add a statement to the link to the source something like "licensed [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/)", because that's what the license forces us to do: 

image

Thanks!

Best,
Robert

**Comment by marabuuu** [comment]
Thank you for your input and reminding me about licensing @haesleinhuepf! I have now incorporated the license check into the script. If there is anything else you see that needs adjustment, I am happy to do so.

**Comment by haesleinhuepf** [comment]
Hi @marabuuu ,

thanks again for working on this! I just tested it by running these commands locally:

```
python scripts/generate_link_lists.py
python scripts/export_csv.py
jupyter-book build docs/
```

And this resulted in a webpage that looks like this, not showing the image because it was stored in a wrong folder (relatively from the readme).

image

I also added the title of the publication after a short discussion with bob: https://github.com/NFDI4BIOIMAGE/training/issues/355

I updated the code and now it looks like this:

image

**Comment by marabuuu** [comment]
Thank you for your modifications and explanation @haesleinhuepf , makes total sense ⭐️

**Pull request merged**
