### PR TITLE
Add new entries to YML file

### LINKED ISSUE #63: MArch 2024 workshop: links to training materials
We should go through these links and check if we have them in our database and otherwise poentially add them:
				
https://www.ugent.be/en/research/openscience/datamanagement	https://www.go-fair.org/resources/rdm-starter-kit/	forschungsdaten.info		
https://f1000research.com/slides/11-746				
https://www.mdpi.com/2304-6775/5/1/2	https://www.nature.com/articles/sdata201618			
https://www.go-fair.org/fair-principles/	https://www.nature.com/articles/sdata201618	https://www.nature.com/articles/s41431-018-0160-0		
https://pubmed.ncbi.nlm.nih.gov/36371407/	https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9271325/	https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8606015/		
Griffin, P., et al., Best practice data life cycle approaches for the life sciences [version 2; peer review: 2 approved]. F1000Research, 2018. 6(1618). DOI: https://doi.org/10.12688/f1000research.12344.2 	https://doi.org/10.11588/heidok.00029489	https://rdmkit.elixir-europe.org/data_life_cycle	https://tess.elixir-europe.org/search?q=data+life+cycle#materials	https://www.ibiology.org/online-biology-courses/bioimage-analysis-course/
https://bausteine-fdm.de/article/view/7945	https://www.o-bib.de/bib/article/view/2018H2S1-13	https://discovery.ucl.ac.uk/id/eprint/1546596/1/26_Learn_Guidance_137-140.pdf		
https://dsw.fairdata.solutions/	https://base4nfdi.de/images/AbstractDMP4NFDI.pdf	https://ds-wizard.org/	https://rdmorganiser.github.io/	https://focalplane.biologists.com/2023/11/06/creating-a-research-data-management-plan-using-chatgpt/
				
				
				
				
Sharing & Licensing, https://f1000research.com/slides/10-519 	https://hup.sub.uni-hamburg.de/oa-pub/catalog/book/205			
				
The Carpentries				
Schmidt, C., Bortolomeazzi, M., Boissonnet, T., Fortmann-Grote, C., Dohle, J., Zentis, P., Kandpal, N., Kunis, S., Zobel, T., Weidtkamp-Peters, S., & Ferrando-May, E. (2023). I3D:bio's OMERO training material: Re-usable, adjustable, multi-purpose slides for local user training. Zenodo. https://doi.org/10.5281/zenodo.8323588 	https://omero-guides.readthedocs.io/en/latest/fiji/docs/index.html	Fiji plugin "simple-omero-client"	Fiji plugin "omero_batch-plugin"	
https://omero-guides.readthedocs.io/en/latest/python/docs/gettingstarted.html 	https://docs.openmicroscopy.org/omero/5.6.0/developers/Python.html 	https://github.com/ome/omero-guide-python		
https://wiki-biop.epfl.ch/en/data-management/omero/qupath	https://omero-guides.readthedocs.io/en/latest/qupath/docs/index.html			
				
https://usegalaxy-eu.github.io/posts/2020/11/23/OMERO-post/	https://training.galaxyproject.org/			
BIOMERO				
				
https://gerbi-gmb.de/i3dbio/i3dbio-rdm/i3dbio-bioimage-metadata/				
( https://guide-kvpairs-scripts.readthedocs.io/en/latest/ -> will be moved to omero-guides)	Excel sheet with Macros for dropdown and export as .csv	Annotations using Tabbles and OMERO.script	Fiji plugin "simple-omero-client"	Fiji plugin "omero_batch-plugin"
				
REMBI , https://genomebiology.biomedcentral.com/articles/10.1186/gb-2005-6-5-r47	NBO	QUAREP-LiMi	https://gerbi-gmb.de/i3dbio/i3dbio-rdm/i3dbio-bioimage-metadata/	https://www.frontiersin.org/journals/neuroscience/articles/10.3389/fnins.2022.871228/full
https://www.ebi.ac.uk/bioimage-archive/rembi-help-overview/	https://www.nature.com/articles/s41597-023-02367-w			
				
GitHub - cmohl2013/omero-arc: Library to export OMERO projects to ARC repositories https://www.fdm.tu-clausthal.de/fileadmin/FDM/documents/Manual_eLab_v0.3_20200323.pdf				
				
				
				
				
				
https://focalplane.biologists.com/2021/09/04/collaborative-bio-image-analysis-script-editing-with-git/				
				
				
				
http://opendatahandbook.org/guide/en/what-is-open-data/	https://www.fosteropenscience.eu/learning/use-open-data-in-teaching/#/id/5b06ca3ba8216e322da360b6			
https://web.library.uq.edu.au/blog/2022/03/five-great-reasons-share-your-research-data	https://www.publisso.de/en/advice/publishing-advice-faqs/research-data			
https://gerbi-gmb.de/i3dbio/i3dbio-rdm/image-data-repositories/	10.12688/f1000research.121714.2			
https://gerbi-gmb.de/2023/06/01/finding-and-choosing-a-repository/	https://www.re3data.org/			
https://www.go-fair.org/fair-principles/				
				
Cultlivating Open Training (Slides) https://zenodo.org/records/10654775	https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/			
https://www.ebi.ac.uk/bioimage-archive/submit/	https://www.sciencedirect.com/science/article/pii/S0022283622000791?via%3Dihub			
https://www.nature.com/articles/nmeth.4326				
https://focalplane.biologists.com/2023/02/15/sharing-research-data-with-zenodo/	https://focalplane.biologists.com/2023/07/26/sharing-your-poster-on-figshare/			
				
				
				
nfdi.de	forschungsdaten.info			
				
				
				
				
				
				
				
				
				
				
				
				
				
				
Cultlivating Open Training (Slides) https://zenodo.org/records/10654775	https://doi.org/10.1371/journal.pcbi.1007854			
				
				
				
				
				
Data Stewardship goes Germany	https://www.nature.com/articles/s41431-018-0160-0			
				
				
				
				
				
				
https://omero-fbi.fr/slides/elmi23_cfd/main.html#/title-slide				
Youtube channel OME	Youtube channel Glencoe	Youtube videos Eric Ratamero	I3D:bio training material collection	
https://www.orca.nrw/searchresults?searchbox=%22elabftw%22&orca_show_all_of=result_media				
https://nfdi4plants.org/nfdi4plants.knowledgebase/index.html				
OMERO-cli-transfer tool				
				
				
NGFF spec/schema	NGFF validator			
https://www.glencoesoftware.com/products/ngff-converter/	https://github.com/glencoesoftware/bioformats2raw	https://github.com/glencoesoftware/raw2ometiff	BioFormats CLI toolkit	
				
				
https://www.nature.com/collections/djiciihhjh	https://forum.image.sc/t/checklists-for-publishing-images-and-image-analysis/86304			
https://workflowhub.eu/	https://galaxyproject.org/learn/advanced-workflow/	https://galaxy-au-training.github.io/tutorials/modules/workflows/		
https://training.galaxyproject.org/	https://www.knime.com/community/image-processing			
https://focalplane.biologists.com/2022/12/08/managing-scientific-python-environments-using-conda-mamba-and-friends/

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Hi @lea-33 ,

this is a folllow-up PR for #320. I presume git-bob didn't work because you worked on a fork, and there github-secrets were not configured as [demonstrated here](https://github.com/haesleinhuepf/git-bob/blob/main/docs/installation-tutorial.md). I merged it into a new branch on the source repositories, where the secrets are configured. Hence, we can see here in a minute if git-bob works, and if the other tests are passing.

I will also write the following so that the related issue is closed automatically, once this PR is merged:

closes #63

Best,
Robert

### CODE REVIEW

**Comment by lea-33** [comment]
Thanks! The git-bob is working now. So we just have to solve the issue with the data normalizer and then it should be working to merge it.

**Comment by haesleinhuepf** [comment]
The current error is related to entries which have no tags. 
```
Traceback (most recent call last):
  File "/home/runner/work/training/training/scripts/generate_link_lists.py", line 429, in <module>
    main()
  File "/home/runner/work/training/training/scripts/generate_link_lists.py", line 54, in main
    all_author_counts = collect_all(content, "authors")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/training/training/scripts/generate_link_lists.py", line 322, in collect_all
    if type(tags) is not list and "," in tags:
                                  ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

I will take care of this.

**Comment by haesleinhuepf** [comment]
The error is now:
```
Duplicate entry detected: https://zenodo.org/records/8323588
Duplicate entry detected: https://doi.org/10.5281/zenodo.8323588
Duplicate entry detected: https://www.nature.com/articles/s41592-021-01166-8
Duplicate entry detected: https://www.go-fair.org/fair-principles/
Traceback (most recent call last):
  File "C:\structure\code\training\scripts\generate_link_lists.py", line 433, in <module>
    main()
  File "C:\structure\code\training\scripts\generate_link_lists.py", line 74, in main
    raise KeyError(f"Duplicate entries detected! Remove them and rebuild the index.")
KeyError: 'Duplicate entries detected! Remove them and rebuild the index.'
```

I will take care of this.

**Comment by haesleinhuepf** [comment]
Big thanks @lea-33 !

**Pull request merged**
