### PR TITLE
Merge all yml files into one

### LINKED ISSUE #134: We should combine all yml files in one yml file
Because the differentiation in multiple files doesn't make much sense

CC @SeverusYixin

### PR DESCRIPTION
**Pull request by SeverusYixin**
Hi @haesleinhuepf, would you mind helping me review this code for merging all the yml files into one file? Check if this is the one you want :) 

Interesting, it created a new PR xd.

This PR closes #134

### CODE REVIEW

**Comment by SeverusYixin** [comment]
Its not working. I have a question, if this code merges all the data to a new file, then the new file must have repeated thing with the original files, because we merge it and we didn't delete the original one, am I right understand?

**Comment by haesleinhuepf** [comment]
Correct. That's why you need to delete the old files. Otherwise we have duplicates

**Comment by SeverusYixin** [comment]
it works

**Comment by SeverusYixin** [comment]
I have already removed the scripts.

**Comment by haesleinhuepf** [comment]
Thanks for working on this @SeverusYixin !

Btw. next time with a similar task, consider copy&pasting the yml-files together instead of writing a script which does that. This might go much faster ;-)

**Comment by SeverusYixin** [comment]
> Thanks for working on this @SeverusYixin !
> 
> Btw. next time with a similar task, consider copy&pasting the yml-files together instead of writing a script which does that. This might go much faster ;-)

You are welcome :) "copy&pasting" is a good idea :)  That time, I was thinking of preventing the same data from appearing in different ymls, but of course next time for a multi-yml merge you could just run this script as it merges any yml file in all resource folders.

**Pull request merged**
